mode: aggregate_test
batch_size: 16
epoch: 20
learning_rate: 1e-2
gpu: 0
num_point: 1024
optimizer: SGD
weight_decay: 1e-4
momentum: 0.9
normal: False
random_rotate: False
data_dir: data/modelnet40_normal_resampled/
model_dir: models/point_transformer/
log_dir: log/point_transformer/
checkpoint_freq: 5
output_dir: output/point_transformer/

defaults:
  - _self_
  - model: point_transformer

hydra:
  run:
    dir: log/${mode}_${model.name}/${model.name}_model_rot_${random_rotate}_e_${epoch}

  sweep:
    dir: log/
    subdir: ${mode}_${model.name}/${model.name}_model_rot_${random_rotate}_e_${epoch}
